# Generated by Django 5.0.4 on 2024-04-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='past_match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Cancelled', 'Cancelled'), ('Finished', 'Finished')], max_length=20)),
                ('team_home', models.CharField(blank=True, max_length=100, null=True)),
                ('team_away', models.CharField(blank=True, max_length=100, null=True)),
                ('score_home', models.CharField(blank=True, max_length=20, null=True)),
                ('score_away', models.CharField(blank=True, max_length=20, null=True)),
                ('referee', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('hour', models.TimeField(blank=True, null=True)),
                ('stade_name', models.CharField(blank=True, max_length=100, null=True)),
                ('league', models.CharField(blank=True, max_length=100, null=True)),
                ('phase', models.CharField(blank=True, max_length=100, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
                ('humidity', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
                ('pressure', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
                ('precipitation', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
                ('wind_speed', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
                ('code', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
                ('code_url', models.CharField(blank=True, max_length=100, null=True)),
                ('neutrality', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('nationality1', models.CharField(blank=True, max_length=100, null=True)),
                ('nationality2', models.CharField(blank=True, max_length=100, null=True)),
                ('sporting_nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('club', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('tenure_tenure', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
                ('ratio_match', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
                ('nb_min_played', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('unavailability_date', models.DateField(blank=True, null=True)),
                ('unavailability_reason', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(blank=True, max_length=100, null=True)),
                ('city_club', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='up_match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('In progress', 'In progress')], max_length=20)),
                ('team_home', models.CharField(blank=True, max_length=100, null=True)),
                ('team_away', models.CharField(blank=True, max_length=100, null=True)),
                ('score_home', models.CharField(blank=True, max_length=20, null=True)),
                ('score_away', models.CharField(blank=True, max_length=20, null=True)),
                ('referee', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('hour', models.TimeField(blank=True, null=True)),
                ('stade_name', models.CharField(blank=True, max_length=100, null=True)),
                ('league', models.CharField(blank=True, max_length=100, null=True)),
                ('phase', models.CharField(blank=True, max_length=100, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
                ('humidity', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
                ('pressure', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
                ('precipitation', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
                ('wind_speed', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
                ('code', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
                ('code_url', models.CharField(blank=True, max_length=100, null=True)),
                ('neutrality', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
