# Generated by Django 5.0.3 on 2024-04-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='up_match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('In progress', 'In progress'), ('Finished', 'Finished'), ('Cancelled', 'Cancelled')], max_length=20)),
                ('team_home', models.CharField(blank=True, max_length=100, null=True)),
                ('team_away', models.CharField(blank=True, max_length=100, null=True)),
                ('score', models.CharField(blank=True, max_length=20, null=True)),
                ('referee', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('hour', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('id_stade_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
