# Generated by Django 5.0.4 on 2024-05-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='up_match',
            name='slug',
            field=models.SlugField(blank=True, max_length=600, unique=True),
        ),
    ]
