# Generated by Django 5.0.3 on 2024-04-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='up_match',
            old_name='id_stade_name',
            new_name='stade_name',
        ),
        migrations.AddField(
            model_name='up_match',
            name='league',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
