# Generated by Django 5.0.3 on 2024-04-04 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_id_stade_name_up_match_stade_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='up_match',
            name='location',
        ),
    ]
