# Generated by Django 5.0.3 on 2024-04-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_up_match_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='up_match',
            name='phase',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
