# Generated by Django 5.0.4 on 2024-04-29 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fora', '0004_tchat_match_comment_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tchat_match_comment',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fora.tchat_match_category'),
        ),
    ]
