# Generated by Django 5.0.4 on 2024-04-30 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fora', '0006_tchat_match_category_slug'),
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tchat_match_comment',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='tchat_match_comment',
            name='match_id',
        ),
        migrations.CreateModel(
            name='threads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=600, unique=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fora.tchat_match_category')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.up_match')),
            ],
        ),
        migrations.AddField(
            model_name='tchat_match_comment',
            name='thread',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fora.threads'),
        ),
    ]
