# Generated by Django 5.0.4 on 2024-04-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fora', '0007_remove_tchat_match_comment_categorie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='threads',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
