# Generated by Django 5.0.4 on 2024-04-30 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fora', '0008_threads_closed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='threads',
            old_name='categorie',
            new_name='category',
        ),
    ]
