# Generated by Django 5.0.4 on 2024-05-01 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fora', '0009_rename_categorie_threads_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threads',
            name='slug',
        ),
    ]
