# Generated by Django 5.0.4 on 2024-05-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fora', '0013_rename_slug_tchat_match_category_slug_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tchat_match_category',
            name='slug_country',
            field=models.SlugField(blank=True, max_length=600, null=True),
        ),
    ]
